name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'

      - name: Install dependencies
        run: |
          npm install

      - name: Build Documentation
        run: |
          npm run build

  deploy-site:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
